const products = [
  {
    id: 'price_1JAE9cEy9j6mAC9ettoD2R0D',
    name: 'Kentiapalm (L)',
    price: 3995,
    onSale: true,
    saleDiscount: 10,
    salePrice: 3500,
    currency: 'USD',
    image: '/plants/kentiapalm.png',
    rating: {
      count: 85,
      rate: 4.5,
    },
  },
  {
    id: 'price_1JAEABEy9j6mAC9eYTnD6Rv7',
    name: 'CARTÃO PSN R$ 250 REAIS PLAYSTATION NETWORK BRASIL',
    price: 25000,
    onSale: true,
    salePrice: 24000,
    saleDiscount: 4,
    currency: 'USD',
    image: '/plants/monstera-deliciosa.png',
    rating: {
      count: 137,
      rate: 4.5,
    },
  },
  {
    id: 'price_1JAEAjEy9j6mAC9e1jK4nxds',
    name: 'SUPER MARIO MAKER 2 [DIGITAL]',
    price: 2995,
    onSale: true,
    salePrice: 2095,
    saleDiscount: 14,
    currency: 'USD',
    image: '/plants/paper-mario_m3.webp',
    rating: {
      count: 104,
      rate: 4,
    },
  },
  {
    id: 'price_1JAEBeEy9j6mAC9ewOgehqP6',
    name: 'Cactus Euphorbia (L)',
    price: 4995,
    onSale: false,
    saleDiscount: 0,
    salePrice: 3500,
    currency: 'USD',
    image: '/plants/euphorbia.png',
    rating: {
      count: 213,
      rate: 5,
    },
  },
  {
    id: 'price_1JAEBxEy9j6mAC9eJFypGxjc',
    name: 'Cartão Uber Cash: Crédito Para Uber e Uber Eats - Saldo de R$50',
    price: 5000,
    onSale: true,
    saleDiscount: 5,
    salePrice: 4499,
    currency: 'USD',
    image: '/plants/calathea-orbifolia.png',
    rating: {
      count: 78,
      rate: 4,
    },
  },
  {
    id: 'price_1JAECJEy9j6mAC9epK9RoNwV',
    name: 'The Witcher 3: Wild Hunt - Game of the Year Edition',
    price: 2995,
    onSale: false,
    saleDiscount: 0,
    salePrice: 3500,
    currency: 'USD',
    image: '/plants/the-witcher.webp',
    rating: {
      count: 89,
      rate: 5,
    },
  },
  {
    id: 'price_1JAECWEy9j6mAC9eapjaRm9M',
    name: 'CÓDIGO DO GOOGLE PLAY R$ 100',
    price: 1000,
    onSale: false,
    saleDiscount: 0,
    salePrice: 0,
    currency: 'USD',
    image: '/plants/calathea-ornata.png',
    rating: {
      count: 271,
      rate: 5,
    },
  },
  {
    id: 'price_1JAECpEy9j6mAC9etXk35nRL',
    name: 'A Product Name that is big as hell - super cool edition - so big ...',
    price: 38995,
    onSale: true,
    saleDiscount: 35,
    salePrice: 28995,
    currency: 'USD',
    image: '/plants/street-f-v.jpg',
    rating: {
      count: 78,
      rate: 4,
    },
  },
];

export default products;
